name: pnpm publish

on: [push]

jobs:
  publish:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: â¬‡ï¸ Checkout source code
        uses: actions/checkout@v2

      - name: â” Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/

      - name: ğŸ“¦ Install pnpm
        run: npm install -g pnpm

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ— Publish npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MTS_CHATBOT_NPM_ACCESS_TOKEN }}